// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkUslnqDSe0hiFj5wIlta5g94YQ-Bnpc',
    appId: '1:811481775179:web:22436527ead64b4529a1ce',
    messagingSenderId: '811481775179',
    projectId: 'rokoapp-8222e',
    authDomain: 'rokoapp-8222e.firebaseapp.com',
    storageBucket: 'rokoapp-8222e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN3lnk87zAcH_DMVIxWJDdtNFxdV0Jt48',
    appId: '1:811481775179:android:5a0bc5f3213a218e29a1ce',
    messagingSenderId: '811481775179',
    projectId: 'rokoapp-8222e',
    storageBucket: 'rokoapp-8222e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfhFxRfoUfl4R1coPB8VdDbnh5IC9HDwc',
    appId: '1:811481775179:ios:014c10a1ccf47eed29a1ce',
    messagingSenderId: '811481775179',
    projectId: 'rokoapp-8222e',
    storageBucket: 'rokoapp-8222e.appspot.com',
    iosBundleId: 'com.example.rokoApp1',
  );

}